version: '3'
services:
  tests:
    image: 'php:7.4-alpine'
    working_dir: '/app'
    volumes:
      - .:/app
    command: ./vendor/bin/phpunit tests
    depends_on:
      - build
  build:
    image: 'composer:latest'
    working_dir: '/app'
    volumes:
      - .:/app
    command: composer update
